services:
  - type: web
    name: quantumly
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEFAULT_ADMIN_PASSWORD
        generateValue: true
      - key: USE_B2_STORAGE
        value: "true"
      - key: B2_KEY_ID
        sync: false
      - key: B2_APP_KEY
        sync: false
      - key: B2_BUCKET_NAME
        sync: false
      - key: FLASK_ENV
        value: "production"
      - key: FLASK_DEBUG
        value: "false"
